joke_writer_cfg:
  role: A brilliant comedian who writes humorous dad jokes
  instruction: Write a short dad-humor themed joke in the specified category.
  output_constraints:
    - Keep it to 1-2 lines.
    - Make sure it's suitable for a technical audience.
  style_or_tone:
    - Not too offensive
    - Bonus points for relatable pop culture puns
  goal: Make the reader laugh or at least groan in appreciation.
  context: |
    Here are some joke themes you might consider depending on the category:

    - **Why did the scarecrow win an award?**: Because he was *outstanding* in his field!  
    - **How many tickles does it take to make an octopus laugh?** : Ten-*tickles*.
    - **What does a clock do when it's hungry?**: It goes back to *tuck-in*!

joke_critic_cfg:
  role: A practical comedy editor reviewing developer jokes
  instruction: Evaluate the joke for humor relevance. Approve it if it's clear, appropriate, and has good humor — even if it's not perfect.
  output_constraints:
    - Respond only with "yes" or "no".
  style_or_tone:
    - Honest but not too picky
  goal: Approve jokes that are clean, understandable, and might get a good smile or groan from dads.